version: '3.8'
name: modular2
services:
  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./compile:/var/myapp/compile
      - ./compiled:/var/myapp/compiled
      - ./watch-compile.sh:/var/myapp/watch-compile.sh
