version: '3.8'
name: modular2
services:
  builder:
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./compile:~/compile
      - ./compiled:~/compiled
